name: Pipeline

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Julia 1.7
      uses: julia-actions/setup-julia@latest
      with:
        version: 1.7
    - name: Build package
      uses: julia-actions/julia-buildpkg@latest
      with: 
        project: "SymbolicErrorPropagator"
    - uses: julia-actions/julia-runtest@latest
      with: 
        project: "SymbolicErrorPropagator"
